apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-dms
  labels:
    app: nginx-dms
spec:
  selector:
    matchLabels:
      app: nginx-dms
  template:
    metadata:
      labels:
        app: nginx-dms
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
