apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-nodeselector
  labels:
    app: nginx-nodeselector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-nodeselector
  template:
    metadata:
      labels:
        app: nginx-nodeselector
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
