apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pluscode-autoscaler
spec:
  targetCPUUtilizationPercentage: 30
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pluscode-demo