apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: pluscode-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pluscode-demo
  metrics:
  - type: External
    external:
      metricName: loadbalancing.googleapis.com|https|request_count
      metricSelector:
        matchLabels:
          resource.labels.forwarding_rule_name: k8s2-fr-pqqby6yf-default-pluscode-ingress-hrsjzvkf
      targetAverageValue: 5